### ISSUE TITLE
ImportError: No module named moses

### ISSUE THREAD

**Issue by mzeidhassan** [anoidgit/NMTServer#1]
First, thanks for your contribution. I appreciate it.
 I am trying to run your server, but I keep getting this error:

`Traceback (most recent call last):
  File "C:/Users/home/OneDrive/introduction to NLP/modernmt/OpenNMTServer-master/NMTServer-master/userver.py", line 3, in <module>
    import translate
  File "C:\Users\home\OneDrive\introduction to NLP\modernmt\OpenNMTServer-master\NMTServer-master\translate.py", line 10, in <module>
    import detoken
  File "C:\Users\home\OneDrive\introduction to NLP\modernmt\OpenNMTServer-master\NMTServer-master\detoken.py", line 1, in <module>
    from nltk.tokenize.moses import MosesDetokenizer
ImportError: No module named moses`

By the way, I installed the module and I am not sure why I am keeping getting this error.
I wish you created a requirements file. It would have made things easier.

I assume this was created for Python 2.7, not 3.6, right? 

One more thing:
My engine is EN-AR, so I don't think Chinese segmentation. Do you think it would be OK to just delete seg.py file and all references to pynlpir?

By the way, the demo is down. Can you please double check ?

Thanks

**Comment by hfxunlp** [comment]
Sorry for I do not know whether AR need detokenize or not, but I think English should be tokenized (same as word segmentation procedure for Chinese) before you input to the model. In this case, you have to define your own tokenize implementation in `token.py`, which should contains `poweon`(Initiate your tokenizer, `pass` is ok if you do not need), `poweroff`(free your tokenizer, `pass` is ok if you do not need) and `tokenone`(tokenize one English sentence). If the generation of AR do not need to be detokenized, you can just comment the line where imports `detoken.py`. and remove the call to `detoken` in `_translate` function of `translate.py`. You can remove `char2pinyin` (with call to it in `translate.py`) and importation of `pinyin` package in `datautils.py`, because it is also a special case for Chinese. You should also change the definition of `splitcode` in `datautils.py` which controls how to split a paragraph into sentences before translation.
These code contains these 8 steps:

1. tokenize the source paragraph;(`token.py`, for Chinese it is Chinese word segmentation)

2. cut the tokenized source paragraph into sentences;(`datautils.py`, `splitcode` and `cutParagraph`)

3. dump the sentences into a batch of data within json format;(`makeBatch` in `datautils.py`, call to `json.dumps` in `_translate` function of `translate.py`)

4. send the json format data with zmq to the OpenNMT translate server, and receive the translation result;(`_translate_core` in `translate.py` in which function also defines the IP address and port of translation server)

5. restore the json format translation into a batch of sentences;(`json.loads` in `_translate` of `translate.py`)

6. restore a batch of sentences to a paragraph;(`datautils.py`, `restoreFromBatch`)

7. transform the Chinese characters in the target paragraph into their pinyin format;(special for Chinese. `import pinyin` and `char2pinyin` function in `datautils.py`)

8. detokenize the target translation.(`detoken.py`, `detoken`)
This whole process is shown at [`_translate`](https://github.com/anoidgit/NMTServer/blob/master/translate.py#L20) function in `translate.py`. I hope things can be a little bit clearer.
Sorry for my poor English and ugly code. You could try the [rest translation server](https://github.com/OpenNMT/OpenNMT/blob/master/tools/rest_translation_server.lua) implemented by OpenNMT which should be more helpful and easy to use.

**Comment by mzeidhassan** [comment]
Thanks for your reply. Your English is perfect by the way.

I think it's better to go with OpenNMT rest translation server, but it's still not clear how to send a POST request to get translation returned.  Do you have any idea what is needed to make this up and running. What I would like to achieve is to have a small web page/app with a text filed where you can basically put the text to translate there and once I click 'Submit' button, the translation will be returned. I managed to get this working for ModernMT, but not for OpenNMT.

**Comment by hfxunlp** [comment]
If you can set up a rest translation server, It is not quite hard to design a simple website to send a post and receive a reply with the help of Flask, a python library which can achieve this. 
You can see `userver.py` which shows how to assign functions for `GET` and `POST` methods and `translate.html` in `templates/` which demonstrates an acceptable template of Flask and how to post a form to `userver.py` by html. 
Feel happy if I could help you.

**Comment by mzeidhassan** [comment]
Thank you so much @anoidgit  for being so supportive and helpful.  I managed to run the server at a remote machine at home, but for some reason, the connection seems to be blocked when I try to translate a sentence or so using this command taken from http://opennmt.net/OpenNMT/tools/servers/

`curl -v -H "Content-Type: application/json" -X POST -d '[{ "src" : "Hello World" }]' http://192.168.1.166:7784/translator/translate
`

So, if OpenNMT is installed on a different machine, do you need to change the host in this line of code in _userver.py_ to the remote machine IP:

`if __name__ == '__main__':
	app.run(port=8888, debug=False, host="0.0.0.0")
	translate.poweroff()`

Is there any other places where I should make the change?

Thanks again for your support!

**Comment by hfxunlp** [comment]
This is the address and port of the web server. Actually, you should implement another `translate.py` which post the source sentence to the translate server and return the corresponding translation.
